livereload: true
timezone: America/New_York

title: Ktt Development

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "github"
    values:
      layout: "article"
  - scope:
      path: "repo"
    values:
      layout: "repository"

exclude:
  - "CNAME"
  - "LICENSE"
  - ".gitignore"
  - "README.md"
  - "/_plugins"

compress_html:
  clippings: []
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []